# Generated by Django 3.2.9 on 2022-03-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='humanID',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Benz', max_length=100)),
                ('color', models.CharField(default='Black', max_length=100)),
                ('price', models.IntegerField(default=80000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.human')),
            ],
        ),
    ]
