# Generated by Django 3.2.9 on 2022-03-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20220306_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
